LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
#KEY_OVERRIDE_ENABLE = yes
SRC += features/achordion.c
SRC += features/custom_shift_keys.c
SRC += features/layer_lock.c
KEY_OVERRIDE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
AUTOCORRECT_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
LEADER_ENABLE = yes
#DEBOUNCE_TYPE = sym_eager_pk
# CONSOLE_ENABLE = yes
